<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;


class StrukturSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('strukturs')->insert([
        ['ID'=>1,
        'jabatan'=>'Direktur Utama',
        'nama_organisasi'=>	'Pesonna Optima Jasa',
        'parent_id'=>null,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-DIR/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-DIR/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/DIR/{month}/{year}'],
        
        ['ID'=>2,
        'jabatan'=>'Direktur',
        'nama_organisasi'=>	'Pesonna Optima Jasa',
        'parent_id'=>1,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-DIR/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-DIR/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/DIR/{month}/{year}'],
        
        ['ID'=>3,
        'jabatan'=>'General Manager',
        'nama_organisasi'=>	'Divisi Keuangan dan TI',
        'parent_id'=>2,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-KEU/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-KEU/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/KEU/{month}/{year}'],
        
        ['ID'=>4,
        'jabatan'=>'General Manager',
        'nama_organisasi'=>	'Divisi Bisnis Rental dan Usaha Lain',
        'parent_id'=>2,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-RENTAL/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL/{month}/{year}'],
        
        ['ID'=>5,
        'jabatan'=>'General Manager',
        'nama_organisasi'=>	'Divisi Bisnis Outsourcing dan Jasa Pengamanan',
        'parent_id'=>2,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-OJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-OJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/OJP/{month}/{year}'],
        
        ['ID'=>6,
        'jabatan'=>'General Manager',
        'nama_organisasi'=>	'Divisi SDM dan Logistik',
        'parent_id'=>2,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-SDMLOG/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-/SDMLOG/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SDMLOG/{month}/{year}'],
        
        ['ID'=>7,
        'jabatan'=>'Kepala',
        'nama_organisasi'=> 'SPI Satuan Pengawas Intern',
        'parent_id'=>1,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-SPI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SPI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SPI/{month}/{year}'],
        
        ['ID'=>8,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Departemen Bisnis Rental dan Usaha Lain',
        'parent_id'=>4,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-RENTAL/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL/{month}/{year}'],
        
        ['ID'=>9,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Departemen Pemasaran dan Pengembangan',
        'parent_id'=>4,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-PM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PM/{month}/{year}'],
        
        ['ID'=>10,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Depertemen Pengembangan Bisnis Outsourcing dan Jasa Pengamanan',
        'parent_id'=>5,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-PBOJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PBOJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PBOJP/{month}/{year}'],
        
        ['ID'=>11,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Departemen Operasional Bisnis Ourtsourcing dan Jasa Pengamanan',
        'parent_id'=>5,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-OJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-OJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/OJP/{month}/{year}'],
        
        ['ID'=>12,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Departemen Keuangan',
        'parent_id'=>3,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-KEU/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-KEU/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/KEU/{month}/{year}'],
        
        ['ID'=>13,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Depertemen Pengembangan Aplikasi TI',
        'parent_id'=>3,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>14,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Depertemen Operasional dan Infrastruktur TI',
        'parent_id'=>3,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>15,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Depertemen SDM',
        'parent_id'=>6,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-SDM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SDM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SDM/{month}/{year}'],
        
        ['ID'=>16,
        'jabatan'=>'Manager',
        'nama_organisasi'=>	'Departemen Logistik',
        'parent_id'=>6,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-LOG/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-LOG/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/LOG/{month}/{year}'],
        
        ['ID'=>17,
        'jabatan'=>'Senior Auditor',
        'nama_organisasi'=>	'Satuan Pengawas Intern',
        'parent_id'=>7,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-SPI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SPI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SPI/{month}/{year}'],
        
        ['ID'=>18,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Departemen Bisnis Rental dan Usaha Lain',
        'parent_id'=>8,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-RENTAL/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL/{month}/{year}'],
        
        ['ID'=>19,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Departemen Operasional Bisnis Rental dan Usaha Lain',
        'parent_id'=>8,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-RENTAL/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL/{month}/{year}'],
        
        ['ID'=>20,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Departemen Pemasaran',
        'parent_id'=>9,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-PM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PM/{month}/{year}'],
        
        ['ID'=>21,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen Produk Digital',
        'parent_id'=>9,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-PD/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PD/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PD/{month}/{year}'],
        
        ['ID'=>22,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen Pengembangan Bisnis Outsourcing dan Jasa Pengamanan',
        'parent_id'=>10,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-PBOJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PBOJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PBOJP/{month}/{year}'],
        
        ['ID'=>23,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Departemen Operasional Bisnis Ourtsourcing dan Jasa Pengamanan',
        'parent_id'=>11,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-OJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-OJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/OJP/{month}/{year}'],
        
        ['ID'=>24,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Departemen Keuangan',
        'parent_id'=>12,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-KEU/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-KEU/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/KEU/{month}/{year}'],
        
        ['ID'=>25,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen Pengembangan Aplikasi TI',
        'parent_id'=>13,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>26,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen Operasional dan Infrastruktur TI',
        'parent_id'=>14,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>27,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen SDM',
        'parent_id'=>15,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-SDM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SDM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SDM/{month}/{year}'],
        
        ['ID'=>28,
        'jabatan'=>'Assistant Manager',
        'nama_organisasi'=>	'Depertemen Logistik',
        'parent_id'=>16,
        'kategori'=>1,
        'patern_memo'=>'{no}/MM-LOG/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-LOG/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/LOG/{month}/{year}'],
        
        ['ID'=>29,
        'jabatan'=>'Auditor',
        'nama_organisasi'=>	'Satuan Pengawas Intern',
        'parent_id'=>17,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-SPI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SPI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SPI/{month}/{year}'],
        
        ['ID'=>30,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Departemen Bisnis Rental dan Usaha Lain',
        'parent_id'=>18,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-RENTAL-USLA/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL-USLA/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL-USLA/{month}/{year}'],
        
        ['ID'=>31,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Departemen Operasional Bisnis Rental dan Usaha Lain',
        'parent_id'=>19,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-RENTAL-USLA/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-RENTAL-USLA/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/RENTAL-USLA/{month}/{year}'],
        
        ['ID'=>32,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Departemen Pemasaran',
        'parent_id'=>20,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-PM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PM/{month}/{year}'],
        
        ['ID'=>33,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen Produk Digital',
        'parent_id'=>21,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-PD/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-PD/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/PD/{month}/{year}'],
        
        ['ID'=>34,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen Pengembangan Bisnis Outsourcing dan Jasa Pengamanan',
        'parent_id'=>22,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-OJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-OJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/OJP/{month}/{year}'],
        
        ['ID'=>35,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Departemen Operasional Bisnis Ourtsourcing dan Jasa Pengamanan',
        'parent_id'=>23,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-OJP/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-OJP/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/OJP/{month}/{year}'],
        
        ['ID'=>36,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Departemen Keuangan',
        'parent_id'=>24,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-KEU/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-KEU/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/KEU/{month}/{year}'],
        
        ['ID'=>37,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen Pengembangan Aplikasi TI',
        'parent_id'=>25,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>38,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen Operasional dan Infrastruktur TI',
        'parent_id'=>26,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-TI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-TI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/TI/{month}/{year}'],
        
        ['ID'=>39,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen SDM',
        'parent_id'=>27,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-SDM/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SDM/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SDM/{month}/{year}'],
        
        ['ID'=>40,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Depertemen Logistik',
        'parent_id'=>28,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-LOG/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-LOG/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/LOG/{month}/{year}'],
        
        ['ID'=>41,
        'jabatan'=>'Staff',
        'nama_organisasi'=>	'Satuan Pengawas Intern',
        'parent_id'=>29,
        'kategori'=>2,
        'patern_memo'=>'{no}/MM-SPI/POJ/{month}/{year}',
        'patern_nota'=>'{no}/ND-SPI/POJ/{month}/{year}',
        'patern_surat'=>'{no}/POJ/SPI/{month}/{year}'],
        ['ID'=>42,
        'jabatan'=>'Regional Manager',
        'nama_organisasi'=>	'Perwakilan Medan',
        'parent_id'=>2,
        'kategori'=>2,
            'patern_memo'=>'{no}/MM-MEDAN/POJ/{month}/{year}',
                'patern_nota'=>'{no}/ND-MEDAN/POJ/{month}/{year}',
                    'patern_surat'=>'{no}/POJ/MEDAN/{month}/{year}']
        ]);
    }
}
